name: WiFi Boost
options:
  bundleIdPrefix: com.wifiboost
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic

targets:
  WiFi Boost:
    type: application
    platform: macOS
    sources:
      - path: WiFi Boost
        type: group
        excludes:
          - ContentView.swift
    info:
      path: WiFi Boost/Info.plist
      properties:
        LSUIElement: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wifiboost.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_APP_SANDBOX: NO
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    entitlements:
      path: WiFi Boost/WiFiBoost.entitlements
      properties:
        com.apple.security.app-sandbox: false

schemes:
  WiFi Boost:
    build:
      targets:
        WiFi Boost: all
    run:
      config: Debug
